In [1]:
import sys
sys.path.append('..')

import torch
from utils import from_finite_field_to_int_domain

In [2]:
int_res_dict = torch.load('../params/5_iterations_int.tar.gz')
ff_res_dict = torch.load('../params/5_iterations_ff.tar.gz')

In [3]:
# 'data': self.__saved_data,
# 'weight_1': self.__saved_weight_1,
# 'weight_2': self.__saved_weight_2,
# 'label': self.__saved_label,
# 'gradients': self.__saved_gradients,
# 'forward': self.__saved_forward
prime = 2 ** 26 - 5

In [4]:
# data comparison
print(torch.sum(torch.abs(int_res_dict['data'] - from_finite_field_to_int_domain(ff_res_dict['data'], prime)), dim=1))

tensor([0, 0, 0, 0, 0])


In [5]:
# label comparison
print(torch.sum(torch.abs(int_res_dict['label'] - from_finite_field_to_int_domain(ff_res_dict['label'], prime)), dim=1))

tensor([0, 0, 0, 0, 0])


In [16]:
iter = 0
for idx, row in enumerate(int_res_dict['weight_1'][2] - from_finite_field_to_int_domain(ff_res_dict['weight_1'][2], prime)):
    if torch.count_nonzero(row) != 0:
        print(int_res_dict['weight_1'][2][idx])
        print(ff_res_dict['weight_1'][2][idx])
        print(row)
        iter += 1

        if iter == 3:
            break

tensor([ 5, -1,  0,  2,  6,  8, -7, -4,  4,  8,  8,  8,  2, -8,  1, -6, -9,  8,
         7, -9,  2, -1, -2, -4,  4, -5,  3,  5,  7,  3, -9, -6,  5,  2, -7, -5,
         9,  6, -4, -2, -9,  0, -7, -7, -1,  1, -4,  5, -6,  8,  6, -8, -2,  0,
         1,  3,  4,  1, -4,  4, -9, -4, -2, -4])
tensor([       5, 67108858,        0,        2,        6,        9, 67108852,
        67108855,        4,        8,        8,        8,        2, 67108851,
               1, 67108853, 67108850,        8,        7, 67108850,        2,
        67108858, 67108857, 67108855,        4, 67108854,        3,        5,
               7,        3, 67108850, 67108853,        5,        2, 67108852,
        67108854,        9,        6, 67108855, 67108857, 67108850,        0,
        67108852, 67108852, 67108858,        1, 67108855,        5, 67108853,
               8,        6, 67108851, 67108857,        0,        1,        3,
               4,        1, 67108855,        4, 67108850, 67108855, 67108857,
        6

In [8]:
2**26 -5

67108859

In [26]:
# weight comparison
for idx in range(int_res_dict['weight_1'].size(0)):
    print(torch.sum(torch.abs(int_res_dict['weight_1'][idx] - from_finite_field_to_int_domain(ff_res_dict['weight_1'][idx], prime))))

tensor(0)
tensor(82)
tensor(126)
tensor(258)
tensor(305)
tensor(359)


In [27]:
for idx in range(int_res_dict['weight_2'].size(0)):
    print(torch.sum(torch.abs(int_res_dict['weight_2'][idx] - from_finite_field_to_int_domain(ff_res_dict['weight_2'][idx], prime))))

tensor(0)
tensor(0)
tensor(0)
tensor(5)
tensor(6)
tensor(10)


In [32]:
int_res_dict['forward'][0]['input_vector'] - from_finite_field_to_int_domain(ff_res_dict['forward'][0]['input_vector'], prime)

tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],

In [21]:
int_res_dict['gradients'][0]['weight_1_grad'] - from_finite_field_to_int_domain(ff_res_dict['gradients'][0]['weight_1_grad'], prime)

tensor([[ 2, -1,  1,  ...,  1,  3,  8],
        [ 2, -1,  1,  ...,  1,  3,  8],
        [ 2, -1,  1,  ...,  1,  3,  8],
        ...,
        [ 2, -1,  1,  ...,  1,  3,  8],
        [ 2, -1,  1,  ...,  1,  3,  8],
        [ 2, -1,  1,  ...,  1,  3,  8]])